### ISSUE TITLE
Maybe we shouldn't duplicate packages from our own org?

### ISSUE THREAD

**Issue by tpoisot** [EcoJulia/GBIF2.jl#2]
I'm sort of struggling to understand the situation there, maybe @mkborregaard can help me see things through?

We already have GBIF.jl, we are in the process of adding the download API to it, what is the point of GBIF2.jl that cannot be accomplished with a PR to the existing (and published) package?

I'm afraid that the trend of building a second package with the same functionalities done differently is sending a terrible message to would-be users, and is fundamentally detrimental to the aims of EcoJulia as a project.

This is particularly bad because (i) it's not the first time this happens within the org and (ii) this package is introducing even more types, whereas we discussed harmonizing things.

**Comment by rafaqz** [comment]
Wow.

I made some PRs that had little attention at GBIF.jl https://github.com/EcoJulia/GBIF.jl/pull/41. It was faster to do this from scratch that modify the existing package with friction and slow/no PR replies. It was also nice to rethink the architecture. 

This was a days work a few months ago when I was getting frustrated with the other package, and work today getting it cleaned up. It's not worth this amount of concern.

Maybe "thanks for putting the work in to writing a high quality package", would be more appropriate than whatever this comment is.

**Comment by tpoisot** [comment]
I am not going to waste time on the comment about "high quality package". I also would like to point out, as a professional courtesy, that email exists and could be a good way to flag a slow PR.

**Comment by rafaqz** [comment]
I did ping you on github in two places in that PR, from which you received 2 emails.

And you are meaning to say you didn't see the one PR open on your package sitting there for a year unmerged.
